### ISSUE TITLE
消息中心页面问题

### ISSUE THREAD

**Issue by srdgame** [thingsroot/cloud.thingsroot.com#13]
1. 从个人中心将消息中心的链接去掉
2. 左侧增加主页链接
3. 没有消息（服务器返回空列表）时，去除“载入中"
4. 消息列表缺少设备SN列
5. 平台消息列名："离线" 改为内容
6. 平台消息”消息类型“列的内容Status显示为设备状态， Action改为设备操作
7. 平台消息“消息内容”改为“标题” 需要前端进行拼接，而不是从后台来的上面的内容中提取生成
```
{"action": "start", "message": "", "data": {"inst": "HWUPS2000"}, "id": "start EFC43C54-6A34-11E8-8C76-00163E06DD4A's HWUPS2000 1539741996000", "channel": "app"}
```
标题为： 启动应用 HWUPS2000

```
{"action": "upload_comm", "message": "", "data": {"sec": 0, "inst": "HWUPS2000"}, "id": "192929", "channel": "app"}
```
标题为：上传应用 HWUPS2000的报文
```
OFFLINE
```
标题为：设备离线
以此类比

**Comment by ai-cuicui** [comment]
余留问题：
1.平台消息标题拼接
2.平台消息未读提示小红点（新）
